"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype plugin on
filetype indent on
" Set to auto read when a file is changed from the outside
set autoread
set number relativenumber
"Always show current position
set ruler
set cursorline
" Ignore case when searching
set ignorecase
" When searching try to be smart about cases
set smartcase
" Highlight search results
set hlsearch
set showmatch
syntax enable
colorscheme desert
set background=dark
set paste
